# Default values for MyApp2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
replicaCount2: 1

blue: 
  enabled: false
green: 
  enabled: false

productionSlot: blue


release:
  number: c3a97c9.20190311-1806

image:
  repository: 818353068367.dkr.ecr.eu-central-1.amazonaws.com/tony
  deploy_blue: 
  deploy_green: 
  pullPolicy: IfNotPresent

nameOverride: java-app
fullnameOverride: maven-java-app

service:
  type: ClusterIP
  port: 8181

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
      - host: java2.p0pc0rn.cf
        paths: 
          - path: /
            backend: -blue
      - host: java-demo.p0pc0rn.cf
        paths:
          - path: /
            backend: -green

# for each n in paths

# path = [{ host:java2, paths:[{path:[/,/path],backend[-green,-blue]}]}]

# range paths = [{path:[/,/path],backend[-green,-blue]}]

# range paths = [{path: /, backend: -green}], [{path: /path}, backend: -blue}]

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
